Add 'wheel' into the list of required packages in requirements.txt.
Several of the required packages use it, and when it is not available, their
installation fails with the following error:

    error: invalid command 'bdist_wheel'